//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ingredientes
    {
        [Required]
        [DisplayName("Id")]
        public int ing_id { get; set; }
        [Required]
        [DisplayName("Plato")]
        public int pla_id { get; set; }
        [Required]
        [DisplayName("Ingrediente")]
        public string ing_nombre { get; set; }
        [DisplayName("Cantidad")]
        public Nullable<int> ing_cantidad { get; set; }
    
        public virtual plato plato { get; set; }
    }
}
